### ISSUE TITLE
Choosing CSS framework

### ISSUE THREAD

**Issue by biern** [SignHash/signhash-webapp#12]
Main considerations:
- It should be least intrusive
- It should be easy to replace or modify
- Easy to implement and neat

After a short research, I suggest using either of those:
- http://getskeleton.com/
- http://milligram.io/

Both provide just a bare minimum, though skeleton is the thinner one. I'm leaning more towards using milligram. Any other suggestions @jstefanski

**Comment by jksf** [comment]
Visually I find skeleton more appealing. What are benefits of miligram?
