### ISSUE TITLE
Test codeship CI

### ISSUE THREAD

**Issue by biern** [SignHash/signhash-webapp#3]
I'd like to test how their OS plan fits us. @jstefanski it seems I can't make 3rd party access our github. Please enable codeship and paste me your email somewhere so I can add you to the team, I can't find it anywhere.

**Comment by jksf** [comment]
I can't authorize access to GitHub to Codeship. I'm afraid you have to make an owner on Codeship as there may be a problem when owner of Codeship != owner of GitHub.

**Comment by biern** [comment]
@jstefanski  Ok, this might be the problem:
https://help.github.com/articles/enabling-oauth-app-access-restrictions-for-your-organization/
I can't try it since I don't have access to organization settings. Also, I've created another `Core` team by accident, please remove it.

**Comment by jksf** [comment]
I cannot login to CodeShip, it forces me to create a new organization or I get HTTP error 'too many redirects'. I cleaned all cookies, tried in incognito mode, no luck. I'm an idiot or It's terribly broken.

**Comment by biern** [comment]
Anyhow, you did something that fixed the access issue. It finally has allowed me to add a project.

**Comment by jksf** [comment]
I turned off OATH restrictions for the organization. I guess this helped but I am not sure how it affects the security of GitHub. However, I am still unable to use CodeShip and it's really annoying. I get:

> Ask your team to invite you to an existing organization with your email
> code@jakubstefanski.com

**Comment by biern** [comment]
Ok, somehow it removed you from the team. I've added you once again, should be fine now.

**Comment by biern** [comment]
@jstefanski btw, please add a `build-bot` user to the org while we're at it, we might need it later

**Comment by jksf** [comment]
How should I do it? How is it related to CodeShip?

**Comment by jksf** [comment]
Anyway, I gave you `owner` role to the organization.
