### ISSUE TITLE
Load and verify given github user / organization

### ISSUE THREAD

**Issue by biern** [SignHash/signhash-webapp#36]
Since gists won't work for organizations, I suppose we can just use a hardcoded repository name and proof filename. Eg:
https://raw.githubusercontent.com/<user_or_repo>/signhash-proof/master/proof.txt
@jstefanski any remarks here?
Subtask of #31

**Comment by jksf** [comment]
Good idea. Public GitHub repositories are free so that anyone can create one.
I am not sure if it is not too much hustle (create the repository, clone it locally, add the file, push it), but I cannot think of anything better.

**Comment by biern** [comment]
Actually, you can just click through the whole process. 
First, create a repo on github, then click `create new file` and paste the proof declaration template, filling the signer address.

**Comment by jksf** [comment]
Ok, that's much better :+1:
